### ISSUE TITLE
Access to the path denied

### ISSUE THREAD

**Issue by Engineer-of-Stuff** [ElDewrito/ElDorito#498]
When updating to 0.6.0.0, the updater fails. In the log file, this is given:

`2018-05-13 21:17:09.034 -06:00 [Warning] Unknown package restore failure.
System.UnauthorizedAccessException: Access to the path '[my file path]\Halo Online\[literally every Halo Online file]' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at System.IO.File.Delete(String path)
   at DiffBlit.Core.Package.Apply(Path packageDirectory, Path targetDirectory, Boolean validateBefore, Boolean validateAfter, ProgressChangedEventHandler progressHandler, String progressStatus) in F:\Projects\DiffBlit\DiffBlit.Core\Package.cs:line 169`

I ran it as admin.

**Comment by Engineer-of-Stuff** [comment]
It just worked. No idea why this issue I was having for weeks fixed itself when I posted to GitHub.

**Comment by Engineer-of-Stuff** [comment]
You guys can close this thread.
